In [1]:
import os
# os.popen('')
import sys
sys.path.append('/nethome/storage/raid2/o.okewale/damask/python')
import numpy as np
from damask import Grid
from damask import seeds

In [2]:
def createDirectory(dir:str):
    if not os.path.exists(dir):
        os.makedirs(dir)

In [4]:
def grabOrGenerateSeeds(size, number_of_grains, cells):
    inputFolder = 'rves/seeds/'
    createDirectory(inputFolder)
    inputFile = f'{inputFolder}/{size}_{number_of_grains}.seeds.npy'
    if (os.path.exists(inputFile)):
        print("loading from file")
        return np.load(inputFile)
    else:
        print("generating new seeds")
        generated_seeds = seeds.from_random(size,number_of_grains,cells)
        np.save(inputFile, generated_seeds)
        return generated_seeds

In [14]:
def loadOrGenerateSize(number_of_grains, cells, dx):
    inputFolder = 'rves/seeds/'
    createDirectory(inputFolder)
    sizeInputFile = f'{inputFolder}/{number_of_grains}.data.npy'
    if (os.path.exists(sizeInputFile)):
        print("== loading size from file ==")
        size = np.load(sizeInputFile)
        # recalculate cells from size and dx here
        cells_x = int(size[0]/dx)
        newCells = np.array([cells_x,cells_x,cells_x])
        return size,newCells,dx
    else:
        print("== generating new size and saving to file ==")
        size = cells*dx
        np.save(sizeInputFile, size)
        return size,cells,dx

In [15]:
x,y,z = loadOrGenerateSize(2160, np.array([42,42,42]), 8E-06)
x1,y1,z1 = loadOrGenerateSize(2160, np.array([42,42,42]), 4E-06)
x2,y2,z2 = loadOrGenerateSize(2160, np.array([42,42,42]), 2E-06)
print(x,y,z)
print(x1,y1,z1)
print(x2,y2,z2)

== loading size from file ==
== loading size from file ==
== loading size from file ==
[0.000336 0.000336 0.000336] [42 42 42] 8e-06
[0.000336 0.000336 0.000336] [84 84 84] 4e-06
[0.000336 0.000336 0.000336] [168 168 168] 2e-06


In [10]:
grabOrGenerateSeeds(np.array([0.000192,0.000192,0.000192]), 403, np.array([24,24,24]))
grabOrGenerateSeeds(np.array([5.6e-05,5.6e-05,5.6e-05]), 10, np.array([7,7,7]))

loading from file
loading from file


array([[5.30089424e-05, 4.98116461e-06, 3.42811654e-05],
       [4.39705593e-05, 1.91879563e-05, 3.64768710e-05],
       [2.98951888e-05, 5.14597001e-05, 5.26917378e-05],
       [1.17614768e-05, 1.90768734e-05, 1.12448743e-05],
       [3.77670412e-05, 2.77126729e-05, 5.07610408e-06],
       [5.31342059e-05, 2.74010333e-05, 2.79810157e-05],
       [2.71622424e-05, 2.73906548e-05, 1.20411202e-05],
       [4.43031173e-06, 2.89139026e-05, 2.25207059e-06],
       [2.06373615e-06, 1.84398975e-05, 5.13273145e-05],
       [2.15447597e-06, 3.52663313e-05, 2.10912137e-05]])